"""Checks the user-visible page generated by the huddle CLI."""

import json
import re
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class RenderTest(unittest.TestCase):
    def render(self, spec):
        with tempfile.TemporaryDirectory() as directory:
            spec_path = Path(directory) / "question.json"
            html_path = Path(directory) / "question.html"
            spec_path.write_text(json.dumps(spec), encoding="utf-8")
            subprocess.run(
                [sys.executable, str(ROOT / "bin/huddle"), "render", str(spec_path), "-o", str(html_path)],
                check=True,
                capture_output=True,
                text=True,
            )
            return html_path.read_text(encoding="utf-8")

    def test_page_uses_agent_neutral_default_source(self):
        html = self.render({"prompt": "Continue?", "options": ["Yes", "No"]})
        spec = json.loads(re.search(r'<script type="application/json" id="hd-spec">(.*?)</script>', html).group(1))
        self.assertEqual(spec["source"], "Your agent is asking")

    def test_page_preserves_explicit_source(self):
        html = self.render({"prompt": "Continue?", "source": "Codex is asking", "options": ["Yes", "No"]})
        spec = json.loads(re.search(r'<script type="application/json" id="hd-spec">(.*?)</script>', html).group(1))
        self.assertEqual(spec["source"], "Codex is asking")


if __name__ == "__main__":
    unittest.main()
